### ISSUE TITLE
Run navigate.py but get error: ModuleNotFoundError: No module named 'vint_train'

### ISSUE THREAD

**Issue by ZhillerDev** [PrieureDeSion/drive-any-robot#27]
hello @robodhruv , when i run navigate.py with the latest pre_train gnm weight, i got the following error
i try to fix it but nothing works

thank you so much!!!

Loading model from /home/zhiller/workstation/gnm_release/deployment/model_weights/gnm.pth
Traceback (most recent call last):
  File "navigate.py", line 205, in <module>
    main(args)
  File "navigate.py", line 89, in main
    model = load_model(
  File "/home/zhiller/workstation/gnm_release/deployment/src/utils.py", line 31, in load_model
    checkpoint = torch.load(model_path, map_location=device,weights_only=False)
  File "/home/zhiller/miniconda3/envs/gnm_deployment/lib/python3.8/site-packages/torch/serialization.py", line 1097, in load
    return _load(
  File "/home/zhiller/miniconda3/envs/gnm_deployment/lib/python3.8/site-packages/torch/serialization.py", line 1525, in _load
    result = unpickler.load()
  File "/home/zhiller/miniconda3/envs/gnm_deployment/lib/python3.8/site-packages/torch/serialization.py", line 1515, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'vint_train'

**Comment by Lrrrr549** [comment]
Maybe you can use this repo: https://github.com/robodhruv/visualnav-transformer.git

**Comment by ZhillerDev** [comment]
谢谢您的来信哦 = w =
